name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  # make a job name
  unit_tests:
    # configure the operating system 'environment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/unit
          python -m unittest test_utils.py
