name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  # make a job name: running unit tests
  unit_tests:
    # configure the operating system 'environment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: environment.yml
      - run: |
          cd test/unit
          python -m unittest test_utils.py
  
  # job for running pycodestyle
  code_style:
    runs-on: ubuntu-latest
    steps:
      # checkout code again because independent jobs
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: environment.yml
      # $() tells bash to do that command first
      - run: pycodestyle $(git ls-files "*.py")
      
